### PR TITLE
Show dishes

### PR DESCRIPTION
**Pull request by nomad-alt**
### PT link: https://www.pivotaltracker.com/story/show/152637651 ###
- Add dishes on the home page
- Filter by of_type
show dishes pr

### CODE REVIEW

**Comment by diraulo** [comment]
@nurlanemir @magnus-thor The CI setup is working now... make sure you can run the tests locally and fix any issues you have.

And It has nothing to do with `yarn` vs `npm`

**Comment by magnus-thor** [comment]
I know it has nothing to do with yarn vs npm,  but yarn is supposed to deal better with dependencies and I wanted to try that out to see if yarn could clear that problem.

**Comment by diraulo** [comment]
Okay was about to push the fix but I see you got it now. The problem was that you were using an older version of `@angular/core` (4.4.6) and the compiler was at `v5.0.1` obviously there are no compatibilities with those 2. Having a mismatch in dependencies versions will cause you hours of headaches in the JS ecosystem... so watch out for that.

**Review by Sajaas — APPROVED** [review]
Good job!

**Pull request closed without merging**
